var canScroll=!0;$(function(){socket.getDBValue('dashboard_get_events','panelData','data',function(e){if(e.panelData!==null&&e.panelData.length>0){let events=JSON.parse(e.panelData);if(events!==null){let htmlEvents=$('<ul/>',{'class':'recent-events'});for(let i=0;i<events.length;i++){let p=$('<p/>');p.append($('<span/>',{'class':'event-date','html':new Date(events[i].date).toLocaleString()+' '}));p.append($('<span/>',{'class':'label label-primary','html':events[i].type}))
p.append($('<span/>',{'html':' '+helpers.getEventMessage(events[i])}));htmlEvents.append(p)}
htmlEvents.appendTo($('.event-log'))}}
socket.getDBValue('dashboard_get_data','panelData','stream',function(e){if(e.panelData===null){alert('Please allow the bot to generate the data needed to load this page. Try again in 60 seconds...');return}
e=JSON.parse(e.panelData);$('#stream-title').val(e.title);$('#stream-game').val(e.game);if(e.communities.length>0){let c=e.communities.split(',');for(let i=0;i<c.length;i++){$('#stream-community-'+(i+1)).val(c[i])}}
helpers.handlePanelSetInfo($('#dashboard-views').data('number',helpers.parseNumber(e.views)),'dashboard-views');helpers.handlePanelSetInfo($('#dashboard-viewers').data('number',helpers.parseNumber(e.viewers)),'dashboard-viewers');helpers.handlePanelSetInfo($('#dashboard-followers').data('number',helpers.parseNumber(e.followers)),'dashboard-followers');if(e.isLive){$('#dashboard-uptime').html(e.uptime);$('#bg-uptime').removeClass('bg-red').addClass('bg-green')}else{$('#dashboard-uptime').html('Offline');$('#bg-uptime').removeClass('bg-green').addClass('bg-red')}
socket.getDBTableValues('dashboard_get_commands','command',function(e){e.sort(function(a,b){return a.key.localeCompare(b.key)});for(let i=0;i<e.length;i++){$('#custom-command-run').append($('<option/>',{'text':'!'+e[i].key}))}
$('#custom-command-run').select2({placeholder:'Select a Command to Run'}).tooltip('disable');$('#twitch-chat-iframe').html($('<iframe/>',{'frameborder':'0','scrolling':'no','style':'width: 100%; height: 450px; margin-bottom: -5px;','src':'https://www.twitch.tv/embed/'+getChannelName()+'/chat'}));$('#twitch-player-iframe').html($('<iframe/>',{'frameborder':'0','scrolling':'no','style':'width: 100%; height: 450px; margin-bottom: -5px;','src':'https://player.twitch.tv/?channel='+getChannelName()+'&muted=true&autoplay=false'}));$.showPage();$('.event-log').scrollTop($('.recent-events').height())})})})});$(function(){$('input[data-str="text"]').on('input',function(){helpers.handleInputString($(this))});$('#dashboard-views, #dashboard-followers, #dashboard-viewers').on('click',function(e){helpers.handlePanelToggleInfo($(this),e.target.id)});$('#dashboard-btn-update').on('click',function(){socket.sendCommand('update_title','settitlesilent '+$('#stream-title').val(),function(){socket.sendCommand('update_game','setgamesilent '+$('#stream-game').val(),function(){let communities=[];for(let i=1;i<=3;i++){let c=$('#stream-community-'+i);if(c.val().length>0){communities.push(c.val().toLowerCase())}}
socket.sendCommand('update_community','setcommunitysilent '+communities.join(', '),function(){toastr.success('Successfully updated stream information!')})})})});$('#permit-btn').on('click',function(){let obj=$(this).closest('div').find('input');if(obj.val().length>0){socket.sendCommand('permit_user','permit '+obj.val(),function(){toastr.success('Successfully permitted user '+obj.val()+'!');obj.val('')})}});$('#custom-command-run').on('select2:select',function(e){socket.sendCommand('send_command',e.params.data.text.substr(1),function(){toastr.success('Successfully ran command '+e.params.data.text);$('#custom-command-run').val('').trigger('change')})});$('.event-log').on('mouseenter',function(){canScroll=!1});$('.event-log').on('mouseleave',function(){canScroll=!0});helpers.setInterval(function(){helpers.log('Refreshing dashboard data.');socket.getDBValue('dashboard_get_data','panelData','stream',function(e){e=JSON.parse(e.panelData);helpers.handlePanelSetInfo($('#dashboard-views').data('number',helpers.parseNumber(e.views)),'dashboard-views');helpers.handlePanelSetInfo($('#dashboard-viewers').data('number',helpers.parseNumber(e.viewers)),'dashboard-viewers');helpers.handlePanelSetInfo($('#dashboard-followers').data('number',helpers.parseNumber(e.followers)),'dashboard-followers');if(e.isLive){$('#dashboard-uptime').html(e.uptime);$('#bg-uptime').removeClass('bg-red').addClass('bg-green')}else{$('#dashboard-uptime').html('Offline');$('#bg-uptime').removeClass('bg-green').addClass('bg-red')}});socket.getDBValue('dashboard_get_events','panelData','data',function(e){let events=JSON.parse(e.panelData);if(events!==null){let htmlEvents=$('<ul/>',{'class':'recent-events'});for(let i=0;i<events.length;i++){let p=$('<p/>');p.append($('<span/>',{'class':'event-date','html':new Date(events[i].date).toLocaleString()+' '}));p.append($('<span/>',{'class':'label label-primary','html':events[i].type}))
p.append($('<span/>',{'html':' '+helpers.getEventMessage(events[i])}));htmlEvents.append(p)}
$('.event-log').html(htmlEvents);if(canScroll){$('.event-log').scrollTop($('.recent-events').height())}}})},1e4);window.location.hash='#'})